# Włączenie wyświetlacza i zasilania zewnętrznego
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_EXT_POWER=y

# Dedykowana kolejka zadań graficznych (rozwiązuje problem krzaczków w Twojej wersji ZMK)
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
