# Włączenie ekranu i zasilania
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_EXT_POWER=y
# Wymuszenie użycia wbudowanego, czystego widoku ZMK (ZMK Studio/Default UI)
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Wyłączenie niestandardowych animacji (jeśli jakieś znajdowały się w Twoim repozytorium)
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
