# Podstawowe włączenie ekranu i zasilania peryferiów
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_EXT_POWER=y

# Dedykowana kolejka grafiki (pobrana z Twojego działającego configu)
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# WYMUSZENIE WIDOKU TEKSTOWEGO DLA EKRANÓW 128x32
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
